name: wm_dynamics
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - jupyterlab
  - ipykernel
  - h5py
  - pandas
  - scikit-learn
  - tqdm
  - seaborn
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - pip
  - pip:
      - mne
      - nilearn
      - pydmd
      - control
      - cvxpy
      - pysindy
