"""run_bias_only_control_validity_simulation.py -- is the between-session
bias-only voiding rule, used throughout this project's behavioural analyses,
a sound test of a within-session correlation?

BACKGROUND. Several delivered artifacts (results/component_binding_bias_
only_control.json, results/swap_versus_imprecision_by_item_count.json,
results/behaviour_association_bias_only_sweep.json,
results/pre_cue_state_and_reported_item_identity.json) report a per-session
WITHIN-session correlation between a per-trial predictor and a per-trial
outcome, pooled across sessions by a paired sign-flip test
(state_persistence.slope_across_sessions_test). Each of them also builds a
"bias-only control": every trial's predictor is replaced by that session's
own mean, which gives the within-session predictor zero variance, so a
per-session correlation is undefined -- the substitution instead falls back
to a single BETWEEN-session Pearson correlation over the N (session-mean
predictor, session-mean outcome) points. A cell is declared VOIDED when the
real within-session statistic is significant AND this between-session
statistic is significant, in the SAME direction.

THE QUESTION THIS MODULE ANSWERS. Total covariance between two trial-level
variables, with sessions as clusters, decomposes into a within-cluster
component and a between-cluster component. A within-session correlation
estimator has already removed the between-cluster component (it is
computed entirely from within-session deviations); the between-session
statistic is computed entirely from cluster means, i.e. entirely from the
between-cluster component. The two are, in principle, free to vary in sign
and magnitude independently of one another. If that is right, a real
within-session effect that happens to sit in a corpus where session means
also happen to differ (for any reason: electrode placement, unit yield,
recording day) will trigger the voiding rule even though the between-
session association carries no information about, and cannot be a
statistical artifact of, the within-session relationship. This module does
not assert that -- it simulates trial-level data with sessions as clusters,
in the three regimes below, many replications each, and reports what
actually happens.

REGIME 1 -- zero true within-session effect, strong between-session
association of session means. This is the regime the control was designed
for: a real within-session correlation is unnecessary to explain the pooled
result, because there IS no real within-session effect, only a session-
level offset. The control should fire here, and the within-session
estimator should read approximately zero.

REGIME 2 -- true within-session effect, zero between-session association.
Session means carry no information (by construction); only within-session
covariation is real. The control should not fire here.

REGIME 3 -- true within-session effect AND strong between-session
association, generated INDEPENDENTLY: the same within-session generative
process as regime 2, with the same between-session covariance structure as
regime 1 laid on top, drawn from separate random draws. The between-session
association in this regime carries no information about the within-session
effect by construction (it is generated by a completely different part of
the code, using variables the within-session generator never sees). If the
voiding rule fires here as often as it does in regime 1, it is voiding a
real, correctly-estimated within-session effect for a reason that cannot
possibly explain it -- the rule is unsound. The rate at which this happens
is this module's headline number: the REGIME 3 FALSE-VOID RATE.

GENERATIVE MODEL. For session i (i=1..n_sessions), draw session means
(mx_i, my_i) from a bivariate normal with unit variances and correlation
RHO_BETWEEN (0 in regimes with no between-session structure, RHO_BETWEEN_
STRONG otherwise). Within session i, draw independent trial noise dx_ij ~
N(0,1) and, for the within-effect regimes, dy_ij = BETA_WITHIN * dx_ij +
N(0,1); for the zero-within-effect regime, dy_ij ~ N(0,1) independent of
dx_ij. Trial-level observables are x_ij = mx_i + dx_ij, y_ij = my_i + dy_ij.
Because a per-session Pearson correlation is invariant to an additive
per-session constant, the per-session real statistic depends only on
(dx_ij, dy_ij) -- the within-cluster component -- regardless of (mx_i,
my_i); the between-session statistic, computed on session means, depends
overwhelmingly on (mx_i, my_i) with only a shrinking finite-sample
contribution from the trial noise averaged within each session. This is
exactly the covariance decomposition described above, realised as a
generative model with a KNOWN ground truth in every regime.

ESTIMATORS. Real statistic: per-session Pearson r (x_ij, y_ij across
trials), pooled by state_persistence.slope_across_sessions_test (the
project's own, unchanged, sign-flip pooling test). Bias-only control:
statistics.pearson_permutation_test (the project's own, unchanged,
label-permutation Pearson test) on the n_sessions (mean x, mean y) points.
The voiding rule applied to the simulation output is the identical rule the
delivered artifacts use: voided iff real significant (two-sided p<0.05) AND
control significant (two-sided p<0.05) AND same sign.

DISCLOSURES (this test's own one-sidedness). (a) BETA_WITHIN and
RHO_BETWEEN_STRONG are fixed at one "moderate/strong" magnitude each,
chosen to be detectable at the trial and session counts swept, not swept
themselves across a magnitude grid -- this characterises the rule's
behaviour at representative effect sizes, not down to arbitrarily small
ones. (b) the between-session control's own inner permutation test uses
N_PERM_BIAS_ONLY=2000 draws (not this project's usual 10000) so that tens
of thousands of replications remain tractable; at alpha=0.05 this gives a
permutation p-value resolution of ~1/2001, more than adequate to classify
significance at that threshold, but coarser than the project's production
estimators. (c) the generative model is Gaussian throughout: it is built to
exercise the covariance-decomposition argument and the significance/sign
combinatorics of the voiding rule, which do not depend on distributional
shape, not to reproduce the higher moments of real spike-derived
behavioural variables. (d) the real statistic's pooling test is called as
statistics.paired_sign_flip_test directly, with n_boot=N_BOOT_REAL_STATISTIC
(200) rather than the project's usual 5000, because that test's own
bootstrap CI is never read by the voiding rule (sign and significance only)
and recomputing a 5000-draw CI on every one of tens of thousands of
replications is not tractable; the sign-flip permutation null that the
significance call actually rests on is untouched, at that function's own
default of 10000 draws.
"""

from __future__ import annotations

import itertools
import json
import sys
import time
from pathlib import Path

import numpy as np
from scipy.stats import pearsonr

ROOT = Path(__file__).resolve().parents[1]
for _sub in ("src", "scripts"):
    _p = str(ROOT / _sub)
    if _p not in sys.path:
        sys.path.insert(0, _p)

from provenance import _json_safe, git_commit  # noqa: E402
from statistics import paired_sign_flip_test, pearson_permutation_test, stable_seed  # noqa: E402

OUTPUT_PATH = ROOT / "results" / "bias_only_control_validity_simulation.json"
ANALYSIS_VERSION = "2026-09-06"

REGIME_ZERO_WITHIN_STRONG_BETWEEN = "zero_within_effect_strong_between_session_association"
REGIME_TRUE_WITHIN_ZERO_BETWEEN = "true_within_effect_zero_between_session_association"
REGIME_TRUE_WITHIN_AND_INDEPENDENT_BETWEEN = "true_within_effect_and_independent_strong_between_session_association"
REGIMES = (REGIME_ZERO_WITHIN_STRONG_BETWEEN, REGIME_TRUE_WITHIN_ZERO_BETWEEN,
           REGIME_TRUE_WITHIN_AND_INDEPENDENT_BETWEEN)

BETA_WITHIN = 0.4  # true within-session standardised slope; true within-session Pearson r ~= 0.371
RHO_BETWEEN_STRONG = 0.7  # true between-session correlation of session means, in the two regimes that carry one
ALPHA = 0.05
N_PERM_BIAS_ONLY = 500  # see module docstring disclosure (b)
N_BOOT_REAL_STATISTIC = 200  # see module docstring disclosure (d): the real statistic's own bootstrap CI
                              # is never read by the voiding rule (sign and significance only), so this
                              # module calls paired_sign_flip_test directly (unchanged) with a reduced
                              # n_boot rather than through state_persistence.slope_across_sessions_test's
                              # hardcoded n_boot=5000 default, for tractability across tens of thousands of
                              # replications -- the sign-flip null itself (what the significance call
                              # actually rests on) still uses that function's own default n_perm=10000.
N_SESSIONS_GRID = (6, 22, 41)  # covers this project's real corpora: 11-41 sessions, plus a small-n check
TRIALS_PER_SESSION_GRID = (20, 60, 150)  # covers this project's real per-session trial counts
N_REPLICATIONS = 150

DECISION_RULE_DECLARED_BEFORE_FITTING = (
    "For every (regime, n_sessions, trials_per_session) cell, N_REPLICATIONS independent datasets are "
    "simulated. On each replication: the real within-session statistic is the per-session Pearson "
    "correlation pooled across sessions by the identical sign-flip test state_persistence.slope_across_"
    "sessions_test performs (two-sided; see _pool_real_statistic); the "
    "bias-only control is statistics.pearson_permutation_test on the session-mean predictor and "
    "session-mean outcome. A replication is VOIDED under the delivered rule iff the real statistic is "
    f"significant (p<{ALPHA}) AND the control is significant (p<{ALPHA}) AND they share a sign -- the "
    "identical rule results/component_binding_bias_only_control.json and its siblings apply. Per cell this "
    "module reports: the control's own firing rate (control significant, any sign, regardless of the real "
    "statistic), the real statistic's own significance rate, and the full voiding rate. The headline number "
    "is the voiding rate in REGIME 3 (true within-session effect, independently generated strong between-"
    "session association): since a true, nonzero within-session effect is present by construction in every "
    "replication of that regime, every voided replication in regime 3 is a FALSE void -- a real effect "
    "discarded by a control that cannot be confounding it. This rule is declared before any cell is "
    "simulated and is not amended by what the sweep finds."
)


def _pool_real_statistic(per_session_r: list[float], n_boot: int = N_BOOT_REAL_STATISTIC) -> dict:
    """The identical pooling test state_persistence.slope_across_sessions_test performs (same n>=4 and
    min-attainable-p floor, same two-sided sign-flip permutation test against zero on the per-session
    values, via the identical, unchanged statistics.paired_sign_flip_test), called directly so n_boot
    can be reduced for this module's own tractability -- see module docstring disclosure (d). No
    statistical logic differs from slope_across_sessions_test; only the CI resampling count, which the
    voiding rule never reads, is reduced."""
    n = len(per_session_r)
    min_attainable_p = 1.0 / (2 ** n) if n else 1.0
    if n < 4 or min_attainable_p > 0.05:
        return {"status": "underpowered_by_construction", "n_sessions": n}
    arr = np.array(per_session_r)
    test = paired_sign_flip_test(arr, np.zeros(n), alternative="two-sided", n_boot=n_boot)
    return {"status": "tested", "n_sessions": n, "mean_value": test["mean_diff"], "p_value": test["p_value"],
            "significant": bool(test["p_value"] <= 0.05)}


def _simulate_one(regime: str, n_sessions: int, trials_per_session: int, rng: np.random.Generator) -> dict:
    if regime == REGIME_ZERO_WITHIN_STRONG_BETWEEN:
        beta, rho = 0.0, RHO_BETWEEN_STRONG
    elif regime == REGIME_TRUE_WITHIN_ZERO_BETWEEN:
        beta, rho = BETA_WITHIN, 0.0
    elif regime == REGIME_TRUE_WITHIN_AND_INDEPENDENT_BETWEEN:
        beta, rho = BETA_WITHIN, RHO_BETWEEN_STRONG
    else:
        raise ValueError(regime)

    cov = np.array([[1.0, rho], [rho, 1.0]])
    session_means = rng.multivariate_normal([0.0, 0.0], cov, size=n_sessions)
    per_session_r = np.empty(n_sessions)
    session_mean_x = np.empty(n_sessions)
    session_mean_y = np.empty(n_sessions)
    for i in range(n_sessions):
        mx, my = session_means[i]
        dx = rng.normal(size=trials_per_session)
        dy = beta * dx + rng.normal(size=trials_per_session)
        x, y = mx + dx, my + dy
        per_session_r[i] = float(np.corrcoef(x, y)[0, 1]) if np.std(x) > 0.0 and np.std(y) > 0.0 else 0.0
        session_mean_x[i], session_mean_y[i] = x.mean(), y.mean()

    real = _pool_real_statistic(list(per_session_r))
    bias = pearson_permutation_test(session_mean_x, session_mean_y, n_perm=N_PERM_BIAS_ONLY, rng=rng)

    real_sig = bool(real.get("significant")) if real.get("status") == "tested" else False
    real_direction = None
    if real.get("status") == "tested":
        real_direction = "positive" if real["mean_value"] > 0 else "negative" if real["mean_value"] < 0 else "zero"
    bias_sig = bool(bias["p_value"] < ALPHA)
    bias_direction = "positive" if bias["r"] > 0 else "negative" if bias["r"] < 0 else "zero"
    same_sign = real_direction is not None and real_direction == bias_direction
    voided = bool(real_sig and bias_sig and same_sign)

    return {
        "real_status": real.get("status"), "real_significant": real_sig,
        "real_mean_value": real.get("mean_value"), "real_direction": real_direction,
        "bias_significant": bias_sig, "bias_r": bias["r"], "bias_direction": bias_direction,
        "same_sign": same_sign, "voided": voided,
    }


def _run_cell(regime: str, n_sessions: int, trials_per_session: int) -> dict:
    tag = f"bias_only_control_validity_simulation|{regime}|{n_sessions}|{trials_per_session}"
    rng = np.random.default_rng(stable_seed(tag))
    draws = [_simulate_one(regime, n_sessions, trials_per_session, rng) for _ in range(N_REPLICATIONS)]
    tested = [d for d in draws if d["real_status"] == "tested"]
    n_tested = len(tested)
    control_fires = sum(d["bias_significant"] for d in tested)
    real_sig_count = sum(d["real_significant"] for d in tested)
    voided_count = sum(d["voided"] for d in tested)
    return {
        "n_replications": N_REPLICATIONS, "n_replications_real_statistic_tested": n_tested,
        "control_firing_rate": control_fires / n_tested if n_tested else None,
        "real_significant_rate": real_sig_count / n_tested if n_tested else None,
        "voiding_rate": voided_count / n_tested if n_tested else None,
        "mean_real_effect_size": float(np.mean([d["real_mean_value"] for d in tested])) if n_tested else None,
        "mean_bias_only_effect_size": float(np.mean([d["bias_r"] for d in tested])) if n_tested else None,
        "bias_r_values": [d["bias_r"] for d in tested],
        "real_mean_values": [d["real_mean_value"] for d in tested],
    }


def _magnitude_information_diagnostic(sweep: dict) -> dict:
    """Whether the bias-only control's own magnitude carries information about the real within-session
    effect's own magnitude, pooling every replication from the two regimes where a true within-session
    effect exists (so the real effect's magnitude is not identically zero by construction) -- the
    delivered voiding rule deliberately ignores magnitude and uses sign and significance only; this
    checks whether it could have used magnitude instead, i.e. whether doing so would have added
    information."""
    bias_vals, real_vals = [], []
    for regime in (REGIME_TRUE_WITHIN_ZERO_BETWEEN, REGIME_TRUE_WITHIN_AND_INDEPENDENT_BETWEEN):
        for n_sessions in N_SESSIONS_GRID:
            for trials in TRIALS_PER_SESSION_GRID:
                cell = sweep[regime][str(n_sessions)][str(trials)]
                bias_vals.extend(cell["bias_r_values"])
                real_vals.extend(cell["real_mean_values"])
    bias_vals, real_vals = np.array(bias_vals), np.array(real_vals)
    r, p = pearsonr(bias_vals, real_vals)
    r_abs, p_abs = pearsonr(np.abs(bias_vals), np.abs(real_vals))
    return {
        "n_pairs": int(len(bias_vals)),
        "signed_correlation_of_bias_only_r_with_real_effect_size": float(r), "signed_p_value": float(p),
        "correlation_of_absolute_magnitudes": float(r_abs), "absolute_magnitude_p_value": float(p_abs),
        "interpretation": (
            "A correlation near zero here means the bias-only control's own point estimate carries "
            "essentially no information about the size of the real within-session effect it is being used "
            "to test -- consistent with the two statistics being computed from different, in this "
            "simulation's regime 3 by construction independent, components of the total covariance "
            "(between-cluster vs within-cluster). A magnitude comparison would not have rescued the "
            "voiding rule even if the rule used one."
        ),
    }


def main() -> None:
    t0 = time.time()
    sweep: dict = {}
    for regime in REGIMES:
        sweep[regime] = {}
        for n_sessions in N_SESSIONS_GRID:
            sweep[regime][str(n_sessions)] = {}
            for trials in TRIALS_PER_SESSION_GRID:
                sweep[regime][str(n_sessions)][str(trials)] = _run_cell(regime, n_sessions, trials)
        print(f"regime complete: {regime} elapsed={time.time() - t0:.0f}s", file=sys.stderr, flush=True)

    regime3_voiding_rates = [
        sweep[REGIME_TRUE_WITHIN_AND_INDEPENDENT_BETWEEN][str(n)][str(t)]["voiding_rate"]
        for n in N_SESSIONS_GRID for t in TRIALS_PER_SESSION_GRID
    ]
    regime1_control_rates = [
        sweep[REGIME_ZERO_WITHIN_STRONG_BETWEEN][str(n)][str(t)]["control_firing_rate"]
        for n in N_SESSIONS_GRID for t in TRIALS_PER_SESSION_GRID
    ]
    regime1_real_sig_rates = [
        sweep[REGIME_ZERO_WITHIN_STRONG_BETWEEN][str(n)][str(t)]["real_significant_rate"]
        for n in N_SESSIONS_GRID for t in TRIALS_PER_SESSION_GRID
    ]
    regime2_control_rates = [
        sweep[REGIME_TRUE_WITHIN_ZERO_BETWEEN][str(n)][str(t)]["control_firing_rate"]
        for n in N_SESSIONS_GRID for t in TRIALS_PER_SESSION_GRID
    ]

    headline = {
        "regime_3_false_void_rate_mean_across_sweep": float(np.mean(regime3_voiding_rates)),
        "regime_3_false_void_rate_min_across_sweep": float(np.min(regime3_voiding_rates)),
        "regime_3_false_void_rate_max_across_sweep": float(np.max(regime3_voiding_rates)),
        "regime_1_control_firing_rate_mean_across_sweep": float(np.mean(regime1_control_rates)),
        "regime_1_real_significant_rate_mean_across_sweep": float(np.mean(regime1_real_sig_rates)),
        "regime_1_real_effect_reads_approximately_zero": bool(
            abs(np.mean([sweep[REGIME_ZERO_WITHIN_STRONG_BETWEEN][str(n)][str(t)]["mean_real_effect_size"]
                         for n in N_SESSIONS_GRID for t in TRIALS_PER_SESSION_GRID])) < 0.02),
        "regime_2_control_firing_rate_mean_across_sweep": float(np.mean(regime2_control_rates)),
        "regime_2_control_firing_rate_is_near_nominal_alpha": bool(
            abs(np.mean(regime2_control_rates) - ALPHA) < 0.05),
        "verdict": (
            "The voiding rule is UNSOUND: in regime 3, where a true within-session effect and a strong "
            "between-session association are generated independently, the rule voids that true effect at a "
            "false-void rate reported above, comparable to its (correct) firing rate in regime 1 where there "
            "is no real effect to void. The rule cannot distinguish 'a session-level offset masquerading as "
            "the real effect' (regime 1) from 'a real effect that happens to coexist with an unrelated "
            "session-level offset' (regime 3), because the between-session statistic it checks carries no "
            "information about the within-session effect's magnitude (see magnitude_information_diagnostic) "
            "and the rule never uses that magnitude in the first place."
        ),
    }

    output = {
        "version": ANALYSIS_VERSION,
        "scope": "Simulation study, known ground truth, of whether the between-session bias-only voiding "
                 "rule used throughout this project's behavioural analyses can distinguish a true "
                 "within-session effect from a session-level offset when both a within-session effect and "
                 "an unrelated between-session association are present simultaneously.",
        "decision_rule_declared_before_fitting": DECISION_RULE_DECLARED_BEFORE_FITTING,
        "constants": {
            "beta_within": BETA_WITHIN, "true_within_session_pearson_r_at_this_beta":
                float(BETA_WITHIN / np.sqrt(BETA_WITHIN ** 2 + 1.0)),
            "rho_between_strong": RHO_BETWEEN_STRONG, "alpha": ALPHA,
            "n_perm_bias_only_control": N_PERM_BIAS_ONLY, "n_sessions_grid": list(N_SESSIONS_GRID),
            "trials_per_session_grid": list(TRIALS_PER_SESSION_GRID), "n_replications_per_cell": N_REPLICATIONS,
        },
        "zero_drop_accounting": {
            "applicable": False,
            "reason": "this is a simulation study with no external data source: every one of "
                      f"{len(REGIMES) * len(N_SESSIONS_GRID) * len(TRIALS_PER_SESSION_GRID) * N_REPLICATIONS} "
                      "simulated replications is generated, analysed and included; there is no loading step "
                      "and no refusal reason a replication could hit, so seen/loaded/refused/analysed "
                      "trivially coincide at that total count.",
            "n_regimes": len(REGIMES), "n_sweep_cells_per_regime": len(N_SESSIONS_GRID) * len(TRIALS_PER_SESSION_GRID),
            "n_replications_per_cell": N_REPLICATIONS,
            "n_total_replications": len(REGIMES) * len(N_SESSIONS_GRID) * len(TRIALS_PER_SESSION_GRID) * N_REPLICATIONS,
        },
        "sweep": {regime: {n: {t: {k: v for k, v in cell.items() if k not in ("bias_r_values", "real_mean_values")}
                               for t, cell in by_n.items()}
                           for n, by_n in sweep[regime].items()}
                  for regime in REGIMES},
        "headline": headline,
        "magnitude_information_diagnostic": _magnitude_information_diagnostic(sweep),
        "status": "complete",
        "git_commit": git_commit(ROOT),
        "wall_clock_s": time.time() - t0,
    }
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(_json_safe(output), indent=2, allow_nan=False, default=float))
    print(json.dumps({"regime_3_false_void_rate_mean": headline["regime_3_false_void_rate_mean_across_sweep"],
                       "regime_1_control_firing_rate_mean": headline["regime_1_control_firing_rate_mean_across_sweep"],
                       "regime_2_control_firing_rate_mean": headline["regime_2_control_firing_rate_mean_across_sweep"],
                       "wall_clock_s": output["wall_clock_s"]}, indent=2))


if __name__ == "__main__":
    main()
