"""run_within_session_permutation_control.py -- for every cell this project's
between-session bias-only control voided or left the whole claim untested,
apply a control that CAN confound a within-session estimator: a within-
session permutation of the trial-to-outcome assignment.

WHY. results/bias_only_control_validity_simulation.json demonstrates, by
simulation with known ground truth, that the between-session bias-only
control used throughout this project's behavioural analyses (results/
component_binding_bias_only_control.json, results/swap_versus_imprecision_
by_item_count.json, results/pre_cue_state_and_reported_item_identity.json,
results/behaviour_association_bias_only_sweep.json) cannot distinguish a
real within-session effect from a session-level offset when both are
present at once: the between-session statistic it checks is computed
entirely from cluster (session) means, the within-session statistic is
computed entirely from within-cluster deviations, and the two components of
total covariance are free to vary independently. A voiding built on that
control alone is therefore not evidence against the within-session claim --
it rests on an estimator that cannot confound it.

THE VALID CONTROL. Within each session, shuffle the trial-to-outcome
assignment -- session identity, session means, session sizes and every
between-session structure are left EXACTLY as observed; only which trial
gets which outcome, inside that session (inside each item-count level
separately, where the real statistic pools trial-count-weighted across
levels), is randomised. The full pooled statistic (the same estimator, same
pooling rule, as the real claim) is recomputed on every permutation to build
a null distribution entirely generated by within-session shuffling. If the
real effect's magnitude sits outside that null, session identity cannot
explain it, because session identity was held fixed by construction on
every single draw.

CELLS COVERED (located by searching results/*.json for the delivered
voiding branch names and for keys containing "bias"; enumerated in
full in the output's cells_enumerated block):
  A. component_and_item_binding / component_binding_bias_only_control --
     the pooled, within-item-count-level (levels 2 and 3, trial-count
     weighted) swap association: multi-object macaque corpus, 41 sessions.
     VOIDED by the between-session control (raw statistic).
  B. swap_versus_imprecision_by_item_count -- the identical association at
     the single item-count level 2 grain. VOIDED by the between-session
     control.
  C. pre_cue_state_and_reported_item_identity -- the pre-cue state's
     below-half lean toward the item that will be reported (block_a,
     primary statistic). The delivered decision list has no bias-only
     clause on this branch (a declared gap, not an omission), and the
     bias-only control fires in the same direction at larger magnitude --
     the artifact's own text states the departure "must never be read as a
     per-trial neural result" on that basis.
  D. rate_free_state_geometry_behavior_link (surviving half of this
     project's headline dissociation, cited inside results/behaviour_
     association_bias_only_sweep.json) -- NOT voided (the between-session
     control did not reach significance), but the sweep's own cluster
     bootstrap shows that control was itself underpowered (MDD 0.82 r
     units against a 0.14 reference, while observing r=-0.44 in the
     confounding direction): the sweep's own verdict is that this claim is
     UNTESTED against session identity, not confirmed clean of it.

FRAMING, held throughout this module and its output. A cell whose voiding
rests on the between-session control alone is reported as UNRESOLVED --
neither established nor validly withdrawn -- never as "restored" or
"confirmed". A cell becomes positive again only if it independently
survives the within-session permutation control at its own pre-declared
threshold below, and even then it is reported with its effect size and its
detection floor, never as a return to the pre-voiding status quo.

DECISION RULE, declared before any cell is fitted (BRANCH_DECISION_RULE_
DECLARED_BEFORE_FITTING below): a per-cell branch in terms of the
within-session permutation control, including an explicit inconclusive
outcome, applied identically to every cell.

No corpus loader, per-session correlation estimator, ridge decoder or
reachability gate is forked: every one of iter_watters, watters_behaviour,
_session_arrays, _ridge_decode, _report_following_fraction,
_landed_and_target_index, _landed_identity_check, _object_geometry,
_leave_one_out_unit_directions, _watters_reachability, usable_label,
_behaviour_observables, rate_free_session_arrays, _reachable_sessions
(the Panichello loader) and slope_across_sessions_test is imported
unchanged from the delivered script that already uses it. The only new
code here is the within-session permutation engine itself and the
per-cell wiring that hands it each cell's own trial-level arrays.
"""

from __future__ import annotations

import os

os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"

import json
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
for _sub in ("src", "scripts"):
    _p = str(ROOT / _sub)
    if _p not in sys.path:
        sys.path.insert(0, _p)

from corpus_sessions import data_root, iter_watters, watters_behaviour  # noqa: E402
from provenance import _json_safe, git_commit  # noqa: E402
from state_persistence import slope_across_sessions_test  # noqa: E402
from statistics import minimum_detectable_paired_difference, permutation_pvalue, stable_seed  # noqa: E402

from run_component_and_item_binding import (  # noqa: E402
    CORRECT_REPORT_DISTANCE_THRESHOLD, MIN_TRIALS_FOR_BEHAVIOURAL_CORRELATION, _object_geometry,
)
from run_swap_versus_imprecision_by_item_count import _session_arrays  # noqa: E402
from run_deviation_subspace_decomposition import (  # noqa: E402
    WATTERS_RECOVERABILITY_K_CLASSES, _leave_one_out_unit_directions, _watters_reachability,
)
from run_state_content_link import MIN_CLASSES, MIN_TRIALS_PER_CLASS, usable_label  # noqa: E402
from run_watters_state_geometry import _behaviour_observables  # noqa: E402
from run_pre_cue_state_and_reported_item_identity import (  # noqa: E402
    MIN_TEST_TRIALS_PER_SESSION, MIN_TRAIN_TRIALS_PER_SESSION, _landed_and_target_index,
    _landed_identity_check, _report_following_fraction, _ridge_decode, circular_abs_diff,
)
from run_behavior_amplitude_rate_controls import _reachable_sessions as _panichello_reachable_sessions  # noqa: E402
from run_rate_free_state_geometry_behavior_link import _session_arrays as rate_free_session_arrays  # noqa: E402

OUTPUT_PATH = ROOT / "results" / "within_session_permutation_control.json"
ANALYSIS_VERSION = "2026-09-06"
REPRODUCTION_TOLERANCE = 1e-6
N_PERM_WITHIN_SESSION = 10000
MEANINGFUL_EFFECT_THRESHOLD_R_UNITS = 0.14  # this project's standing reference scale (state_behavior_link.json)
ALPHA = 0.05
LEVELS_2_AND_3 = (2, 3)

BRANCH_GATE_FAILED = "void_reproduction_gate_failed"
BRANCH_REAL_NOT_SIGNIFICANT = "inconclusive_the_real_statistic_is_not_significant_on_recomputation"
BRANCH_SURVIVES = "positive_identity_survives_the_within_session_permutation_control"
BRANCH_POWERED_NULL = "powered_null_under_the_within_session_permutation_control"
BRANCH_INCONCLUSIVE_UNDERPOWERED = "inconclusive_below_detection_floor_under_the_within_session_permutation_control"

BRANCH_DECISION_RULE_DECLARED_BEFORE_FITTING = (
    "Applied identically to every cell in this artifact, in order:\n"
    f"  0. If this cell's own reproduction check (recomputed real point estimate against the delivered "
    f"artifact's own number) does not match at tolerance {REPRODUCTION_TOLERANCE}, the branch is "
    f"'{BRANCH_GATE_FAILED}' and no further number is read for that cell.\n"
    "  1. The load-bearing real statistic(s) for this cell (raw, and joint-partial controlling spike "
    "count and trial index, where that partial exists for the estimator) are read from the delivered "
    "artifact. If the real statistic is not itself significant (two-sided p<0.05) -- raw alone for a "
    "cell whose delivered voiding rule only ever checked raw, both raw and joint-partial where the "
    f"delivered rule required both -- the branch is '{BRANCH_REAL_NOT_SIGNIFICANT}', reported with the "
    "real statistic's own minimum detectable difference; the within-session permutation question does "
    "not arise if the cell was never a real positive to begin with.\n"
    "  2. Otherwise, the within-session permutation control is run: session identity, session sizes and "
    "every between-session structure held exactly fixed, only the trial-to-outcome pairing INSIDE each "
    "session (inside each item-count level separately, where the real statistic pools across levels) is "
    f"shuffled, {N_PERM_WITHIN_SESSION} times where the per-draw cost allows, fewer where disclosed. If "
    "the observed pooled statistic's two-sided permutation p-value is below 0.05 for every load-bearing "
    f"statistic checked in step 1, the branch is '{BRANCH_SURVIVES}', reported with the observed effect "
    "size, its whole-session cluster-bootstrap interval, and the permutation p-value's own minimum "
    "attainable value at the number of draws used. This is reported as an independent survival of THIS "
    "control, never as a restoration of, or confirmation of, whatever this claim's status was before the "
    "between-session control was found unsound.\n"
    f"  3. If the permutation p-value is not below 0.05 for at least one load-bearing statistic, and the "
    "real statistic's own whole-session cluster-bootstrap minimum detectable difference is below "
    f"{MEANINGFUL_EFFECT_THRESHOLD_R_UNITS} r units (this project's standing meaningful-effect reference), "
    f"the branch is '{BRANCH_POWERED_NULL}': the within-session shuffle null had the power to separate a "
    "meaningful effect from chance trial-to-outcome pairing within sessions and did not.\n"
    f"  4. Otherwise the branch is '{BRANCH_INCONCLUSIVE_UNDERPOWERED}'.\n"
    "A cell's status is UNRESOLVED, not restored and not confirmed, whenever step 1's between-session "
    "voiding is the only thing being re-examined; only step 2's own pass, reported with its own effect "
    "size and detection floor, licenses calling a cell positive again, and even then only under this "
    "control, at this threshold."
)


# ============================================================================
# Generic within-session permutation engine
# ============================================================================

def _cheap_partial_r(outcome: np.ndarray, covariate: np.ndarray, controls: list[np.ndarray]) -> float | None:
    """Point-estimate-only partial Pearson correlation by the residual method (OLS on
    [intercept, *controls], then Pearson on the two residual series) -- the identical formula
    statistics.partial_correlation_permutation_test uses for its own observed statistic, without that
    function's inner permutation loop, because this helper is called once per session on every one of
    N_PERM_WITHIN_SESSION outer draws, where re-running a full permutation test that many times nested
    inside another permutation test is not tractable."""
    outcome = np.asarray(outcome, dtype=float)
    covariate = np.asarray(covariate, dtype=float)
    if controls:
        design = np.column_stack([np.ones(len(outcome)), *[np.asarray(c, dtype=float) for c in controls]])
        y_resid = outcome - design @ np.linalg.lstsq(design, outcome, rcond=None)[0]
        x_resid = covariate - design @ np.linalg.lstsq(design, covariate, rcond=None)[0]
    else:
        y_resid, x_resid = outcome - outcome.mean(), covariate - covariate.mean()
    if np.std(y_resid) == 0.0 or np.std(x_resid) == 0.0:
        return None
    return float(np.corrcoef(y_resid, x_resid)[0, 1])


def _default_shuffle_block(rng: np.random.Generator, block: dict) -> dict:
    perm = rng.permutation(block["n"])
    return {**block, "outcome": block["outcome"][perm]}


def _circular_outcome_shift(rng: np.random.Generator, block: dict) -> dict:
    shift = int(rng.integers(1, block["n"]))
    return {**block, "outcome": np.roll(block["outcome"], shift)}


def _circular_residual_shift(rng: np.random.Generator, block: dict) -> dict:
    if not block["controls"]:
        return _circular_outcome_shift(rng, block)
    design = np.column_stack([np.ones(block["n"]), *block["controls"]])
    fitted = design @ np.linalg.lstsq(design, block["outcome"], rcond=None)[0]
    residual = block["outcome"] - fitted
    shift = int(rng.integers(1, block["n"]))
    return {**block, "outcome": fitted + np.roll(residual, shift)}


def _default_stat_of_session(blocks: list[dict]) -> float | None:
    """Trial-count-weighted average of each block's own partial correlation -- the identical
    combination rule run_component_and_item_binding.py's _outcome_arm uses to pool a session's own
    per-item-count-level correlations into one within_item_count_level_trial_count_weighted number."""
    weighted, total_n = [], 0
    for block in blocks:
        r = _cheap_partial_r(block["outcome"], block["predictor"], block["controls"])
        if r is None:
            continue
        weighted.append(block["n"] * r)
        total_n += block["n"]
    if total_n == 0:
        return None
    return float(sum(weighted) / total_n)


def within_session_permutation_test(session_blocks: list[list[dict]], seed_tag: str,
                                     n_perm: int = N_PERM_WITHIN_SESSION,
                                     stat_of_session=_default_stat_of_session,
                                     shuffle_block=_default_shuffle_block) -> dict:
    """session_blocks: one entry per session; each entry is a list of blocks (one block per item-count
    level a session's own real statistic pools across; a session with no level structure has exactly
    one block). stat_of_session(blocks) -> the session's own composite statistic (or None). On every
    permutation draw, shuffle_block is applied INDEPENDENTLY to every block of every session (default:
    permutes which trial gets which outcome, inside that block only), session identity, session sizes
    and every between-session and between-block structure held fixed; the pooled statistic (unweighted
    mean of the per-session composites -- the identical pooling statistic
    state_persistence.slope_across_sessions_test's own sign-flip test uses, paired_sign_flip_test's
    mean_diff) is recomputed on every draw to build the null. Two-sided permutation p-value, +1/+1
    corrected (statistics.permutation_pvalue)."""
    rng = np.random.default_rng(stable_seed(seed_tag))
    observed_per_session = [stat_of_session(blocks) for blocks in session_blocks]
    observed_per_session = [v for v in observed_per_session if v is not None]
    if len(observed_per_session) < 2:
        return {"status": "not_computable", "n_sessions_contributing": len(observed_per_session),
                "reason": "fewer than 2 sessions contribute a computable composite value"}
    observed_pooled = float(np.mean(observed_per_session))

    null = np.full(n_perm, np.nan)
    for draw in range(n_perm):
        draw_values = []
        for blocks in session_blocks:
            shuffled = [shuffle_block(rng, block) for block in blocks]
            v = stat_of_session(shuffled)
            if v is not None:
                draw_values.append(v)
        if draw_values:
            null[draw] = float(np.mean(draw_values))
    valid = np.isfinite(null)
    p_value = permutation_pvalue(np.abs(null[valid]) >= abs(observed_pooled))
    return {
        "status": "computed", "n_sessions_contributing": len(observed_per_session),
        "observed_pooled_statistic": observed_pooled,
        "direction": "positive" if observed_pooled > 0 else "negative" if observed_pooled < 0 else "zero",
        "n_permutations_requested": n_perm, "n_permutations_valid": int(valid.sum()),
        "min_attainable_p_value": 1.0 / (n_perm + 1), "p_value": p_value,
        "significant": bool(p_value < ALPHA),
    }


# ============================================================================
# Cells A and B -- multi-object macaque corpus (swap vs deviation)
# ============================================================================

def _qualifying_levels_from_arrays(arrays: dict) -> list[int]:
    """A session qualifies at a level iff it has at least MIN_TRIALS_FOR_BEHAVIOURAL_CORRELATION trials
    at that item-count level -- the identical floor run_component_and_item_binding.py's _outcome_arm
    applies before it will fit a per-level correlation at all, recomputed here directly from the raw
    item_count array rather than from analyse_session's own per_level status field, so this module never
    has to re-run analyse_session's own (expensive, permutation-heavy) per-session correlation fits just
    to learn which levels a session reaches."""
    return [lv for lv in LEVELS_2_AND_3 if int((arrays["item_count"] == float(lv)).sum())
            >= MIN_TRIALS_FOR_BEHAVIOURAL_CORRELATION]


def _blocks_for_levels(arrays: dict, levels: list[int], outcome_key: str, controls: tuple[str, ...]) -> list[dict]:
    blocks = []
    for level in levels:
        mask = arrays["item_count"] == float(level)
        n = int(mask.sum())
        blocks.append({
            "n": n, "predictor": arrays["deviation"][mask], "outcome": arrays[outcome_key][mask],
            "controls": [arrays[c][mask] for c in controls],
        })
    return blocks


def _load_multi_object_corpus() -> tuple[dict[str, dict], dict]:
    root = data_root()
    behaviour = watters_behaviour(root)
    rows_arrays: dict[str, dict] = {}
    n_seen, n_loaded, refused = 0, 0, []
    for session in iter_watters(root, bin_ms=100.0):
        n_seen += 1
        if session["status"] != "loaded":
            refused.append(session["status"])
            continue
        n_loaded += 1
        arrays = _session_arrays(session, behaviour)
        if arrays is not None:
            rows_arrays[session["session"]] = arrays
    zero_drop = {
        "n_seen": n_seen, "n_loaded": n_loaded, "n_refused": len(refused),
        "refusals_by_reason": {r: refused.count(r) for r in sorted(set(refused))},
        "n_with_computable_session_arrays": len(rows_arrays),
        "n_loaded_but_arrays_not_computable": n_loaded - len(rows_arrays),
        "reconciles": bool(n_seen == n_loaded + len(refused)),
    }
    return rows_arrays, zero_drop


def _cell_swap_pooled_within_item_count_level(rows_arrays: dict[str, dict]) -> dict:
    delivered = json.loads((ROOT / "results" / "component_binding_bias_only_control.json").read_text())
    real_delivered = delivered["swap_primary_deviation_within_item_count_level"]
    stat_controls = {"raw": (), "joint_partial_controlling_spike_count_and_trial_index":
                      ("spike_count", "trial_index")}

    session_blocks_by_stat = {stat: [] for stat in stat_controls}
    for arrays in rows_arrays.values():
        levels = _qualifying_levels_from_arrays(arrays)
        if not levels:
            continue
        for stat, controls in stat_controls.items():
            session_blocks_by_stat[stat].append(_blocks_for_levels(arrays, levels, "swap_primary", controls))

    real_recomputed = {}
    for stat in stat_controls:
        per_session = [_default_stat_of_session(blocks) for blocks in session_blocks_by_stat[stat]]
        per_session = [v for v in per_session if v is not None]
        real_recomputed[stat] = slope_across_sessions_test(per_session, alternative="two-sided")

    reproduction_checks = {
        stat: bool(real_recomputed[stat].get("status") == "tested"
                   and abs(real_recomputed[stat]["mean_value"] - real_delivered[stat]["real"]["mean_value"])
                   < REPRODUCTION_TOLERANCE)
        for stat in stat_controls
    }
    gate_ok = all(reproduction_checks.values())

    permutation = {}
    for stat in stat_controls:
        permutation[stat] = within_session_permutation_test(
            session_blocks_by_stat[stat],
            f"within_session_permutation_control|swap_pooled_within_item_count_level|{stat}")

    return _assemble_cell(
        cell_name="swap_vs_imprecision_identity_pooled_within_item_count_level",
        corpus="multi_object_macaque_watters", n_sessions=len(rows_arrays),
        delivered_artifact="results/component_binding_bias_only_control.json",
        reproduction_checks=reproduction_checks, gate_ok=gate_ok,
        real_by_stat={stat: real_delivered[stat]["real"] for stat in stat_controls},
        between_session_control_by_stat={
            stat: real_delivered[stat]["bias_only_between_session"] for stat in stat_controls},
        permutation_by_stat=permutation,
        why_at_risk="the multi-object macaque corpus's pooled, within-item-count-level (levels 2 and 3, "
                    "trial-count weighted) association between the rate-free state-deviation component "
                    "and the saccadic swap indicator -- voided by the between-session control on its raw "
                    "statistic in results/component_binding_bias_only_control.json.",
    )


def _cell_swap_level2_only(rows_arrays: dict[str, dict]) -> dict:
    delivered = json.loads((ROOT / "results" / "swap_versus_imprecision_by_item_count.json").read_text())
    real_delivered_cell = delivered["bias_only_control"]["swap_primary|deviation|level2"]

    session_blocks = []
    for arrays in rows_arrays.values():
        mask = arrays["item_count"] == 2.0
        n = int(mask.sum())
        if n < MIN_TRIALS_FOR_BEHAVIOURAL_CORRELATION:
            continue
        session_blocks.append([{"n": n, "predictor": arrays["deviation"][mask],
                                 "outcome": arrays["swap_primary"][mask], "controls": []}])

    per_session = [_default_stat_of_session(blocks) for blocks in session_blocks]
    per_session = [v for v in per_session if v is not None]
    real_recomputed = slope_across_sessions_test(per_session, alternative="two-sided")
    reproduction_checks = {"raw": bool(
        real_recomputed.get("status") == "tested"
        and abs(real_recomputed["mean_value"] - real_delivered_cell["real_mean_value"]) < REPRODUCTION_TOLERANCE)}
    gate_ok = reproduction_checks["raw"]

    permutation = {"raw": within_session_permutation_test(
        session_blocks, "within_session_permutation_control|swap_level2_only|raw")}

    real_reported = {
        "status": "tested", "mean_value": real_delivered_cell["real_mean_value"],
        "significant": real_delivered_cell["real_significant"],
        "p_value": None,  # not separately stored per-level in the delivered bias-only-control cell
        "note": "p_value for the per-level real statistic is not separately serialised in the delivered "
                "bias_only_control cell (only 'real_significant' and 'real_mean_value' are); "
                "'real_significant' is read from that artifact unchanged.",
    }
    return _assemble_cell(
        cell_name="swap_vs_imprecision_identity_item_count_level_2_only",
        corpus="multi_object_macaque_watters", n_sessions=len(session_blocks),
        delivered_artifact="results/swap_versus_imprecision_by_item_count.json",
        reproduction_checks=reproduction_checks, gate_ok=gate_ok,
        real_by_stat={"raw": real_reported},
        between_session_control_by_stat={"raw": real_delivered_cell["bias_only_between_session"]},
        permutation_by_stat=permutation,
        why_at_risk="the identical swap association restricted to item-count level 2 only (not pooled "
                    "with level 3) -- voided by the between-session control in "
                    "results/swap_versus_imprecision_by_item_count.json.",
    )


# ============================================================================
# Cell D -- rate_free_state_geometry_behavior_link (macaque lPFC single item)
# ============================================================================

def _cell_rate_free_headline() -> dict:
    delivered_claim = json.loads(
        (ROOT / "results" / "behaviour_association_bias_only_sweep.json").read_text())["claims"][
        "rate_free_state_geometry_behavior_link"]
    delivered_pooled = json.loads((ROOT / "results" / "rate_free_state_geometry_behavior_link.json").read_text())[
        "pooled"]

    paths = _panichello_reachable_sessions(data_root())
    stat_controls = {"raw": (), "joint_partial_controlling_spike_count_and_trial_index":
                      ("spike_count", "trial_index")}
    session_blocks_by_stat = {stat: [] for stat in stat_controls}
    n_seen, n_loaded = len(paths), 0
    for path in paths:
        arrays = rate_free_session_arrays(path)
        if arrays is None:
            continue
        n_loaded += 1
        n = len(arrays["is_corr"])
        for stat, controls in stat_controls.items():
            session_blocks_by_stat[stat].append([{
                "n": n, "predictor": arrays["deviation"], "outcome": arrays["is_corr"],
                "controls": [arrays[c] for c in controls],
            }])

    real_recomputed = {}
    for stat in stat_controls:
        per_session = [_default_stat_of_session(blocks) for blocks in session_blocks_by_stat[stat]]
        per_session = [v for v in per_session if v is not None]
        real_recomputed[stat] = slope_across_sessions_test(per_session, alternative="two-sided")

    delivered_key_by_stat = {"raw": "raw_outcome_vs_deviation",
                              "joint_partial_controlling_spike_count_and_trial_index":
                                  "joint_partial_controlling_spike_count_and_trial_index"}
    reproduction_checks = {
        stat: bool(real_recomputed[stat].get("status") == "tested"
                   and abs(real_recomputed[stat]["mean_value"]
                           - delivered_pooled[delivered_key_by_stat[stat]]["mean_value"]) < REPRODUCTION_TOLERANCE)
        for stat in stat_controls
    }
    gate_ok = all(reproduction_checks.values())

    permutation = {}
    for stat in stat_controls:
        permutation[stat] = within_session_permutation_test(
            session_blocks_by_stat[stat], f"within_session_permutation_control|rate_free_headline|{stat}")

    bias = delivered_claim.get("bias_only_between_session", {})
    return _assemble_cell(
        cell_name="rate_free_state_geometry_behavior_link_headline",
        corpus="macaque_lpfc_single_item_panichello", n_sessions=n_loaded,
        delivered_artifact="results/rate_free_state_geometry_behavior_link.json",
        reproduction_checks=reproduction_checks, gate_ok=gate_ok,
        real_by_stat={stat: delivered_pooled[delivered_key_by_stat[stat]] for stat in stat_controls},
        between_session_control_by_stat={stat: bias.get(stat, {"status": "not_available"}) for stat in stat_controls},
        permutation_by_stat=permutation,
        why_at_risk="the surviving half of this project's headline behavioural dissociation: per-trial "
                    "rate-free state deviation vs per-trial trial accuracy, within session, pooled across "
                    "11 macaque lPFC sessions. NOT voided by the between-session control -- but results/"
                    "behaviour_association_bias_only_sweep.json's own cluster bootstrap shows that control "
                    "was itself underpowered (MDD far above the 0.14 r-unit reference, against an observed "
                    "confound of the same sign), so the sweep's own verdict is 'untested', not 'confirmed "
                    "clean of a session-identity confound'.",
        zero_drop_note={"n_seen_reachable": n_seen, "n_loaded": n_loaded},
    )


# ============================================================================
# Cell C -- pre_cue_state_and_reported_item_identity (block_a primary statistic)
# ============================================================================

def _pre_cue_session_trial_arrays(session: dict, behaviour, seed_prefix: str) -> dict | None:
    """Recomputes exactly the sequence run_pre_cue_state_and_reported_item_identity.py's own
    analyse_session runs to reach its block_a primary statistic -- every one of _object_geometry,
    _landed_and_target_index, _landed_identity_check, _behaviour_observables, _leave_one_out_unit_
    directions, _watters_reachability, usable_label and _ridge_decode is imported unchanged and called
    in the identical order with the identical arguments -- but additionally returns the trial-level
    decoded_theta_test, reported_theta and other_theta arrays that function computes internally and
    never returns, because those raw arrays (not exposed by the delivered script) are exactly what a
    within-session permutation of this cell needs. Returns None for any session that does not reach
    'computed' status under the identical gates the delivered script applies; the caller cross-checks
    this function's own primary_fraction against the delivered per-session value before trusting it
    (see the reproduction check in _cell_pre_cue_reported_item)."""
    counts = session["counts"]
    activity = counts.sum(axis=2)
    observables, _excluded, usable = _behaviour_observables(counts, session)
    if int(usable.sum()) < MIN_TRIALS_FOR_BEHAVIOURAL_CORRELATION:
        return None

    geometry = _object_geometry(behaviour, session)
    landed_info = _landed_and_target_index(behaviour, session)
    identity = _landed_identity_check(behaviour, session, geometry, landed_info)
    if not identity["swap_primary_matches_object_geometry"]:
        return None

    item_count = np.asarray(session["num_objects"], dtype=float)
    swap_primary = geometry["swap_primary"]
    train_mask = usable & (item_count >= 2) & (~swap_primary)
    test_mask = usable & (item_count == 3) & swap_primary
    analysis_mask = train_mask | test_mask

    cued_theta = np.asarray(session["cued_theta"], dtype=float)
    theta_mod = np.mod(cued_theta, 2.0 * np.pi)
    discretized_label = (np.floor(theta_mod / (2.0 * np.pi / WATTERS_RECOVERABILITY_K_CLASSES)).astype(int)
                          % WATTERS_RECOVERABILITY_K_CLASSES)

    idx_analysis = np.flatnonzero(analysis_mask)
    if idx_analysis.size < MIN_TRIALS_FOR_BEHAVIOURAL_CORRELATION:
        return None
    label_ok, _reason, label_submask = usable_label(
        discretized_label[idx_analysis], min_classes=MIN_CLASSES, min_per_class=MIN_TRIALS_PER_CLASS)
    if not label_ok:
        return None
    final_idx = idx_analysis[label_submask]

    tag = f"{seed_prefix}|{session['session']}"
    gate = _watters_reachability(counts[final_idx], discretized_label[final_idx],
                                  stable_seed(f"{tag}|reachability"))
    if gate.get("status") != "tested" or not gate.get("cleared", False):
        return None

    train_sub = train_mask[final_idx]
    test_sub = test_mask[final_idx]
    if int(train_sub.sum()) < MIN_TRAIN_TRIALS_PER_SESSION or int(test_sub.sum()) < MIN_TEST_TRIALS_PER_SESSION:
        return None

    unit_vectors_all = _leave_one_out_unit_directions(activity)["unit_vectors"]
    u = unit_vectors_all[final_idx]
    target_2d = np.stack([np.cos(cued_theta[final_idx]), np.sin(cued_theta[final_idx])], axis=1)
    object_theta = landed_info["object_theta"][final_idx]
    landed = landed_info["landed"][final_idx]
    target = landed_info["target"][final_idx]
    other_idx = 3 - target - landed

    fold_seed = stable_seed(f"{tag}|ridge_folds")
    decode_full = _ridge_decode(u[train_sub], target_2d[train_sub], u[test_sub], fold_seed)
    if decode_full.get("status") != "computed":
        return None

    n = np.arange(int(test_sub.sum()))
    reported_theta = object_theta[test_sub][n, landed[test_sub]]
    other_theta = object_theta[test_sub][n, other_idx[test_sub]]
    primary = _report_following_fraction(decode_full["decoded_theta_test"], reported_theta, other_theta)

    return {
        "decoded_theta_test": decode_full["decoded_theta_test"], "reported_theta": reported_theta,
        "other_theta": other_theta, "n_test_trials": primary["n_trials"], "primary_fraction": primary["fraction"],
    }


def _pre_cue_shuffle_block(rng: np.random.Generator, block: dict) -> dict:
    """The identical within-session substitution run_pre_cue_state_and_reported_item_identity.py's own
    _shuffled_report_null uses: independently, per trial, flip a coin on whether 'reported' and 'other'
    are swapped, leaving the decoded position (this session's real, trial-varying decode) untouched."""
    flip = rng.random(block["n"]) < 0.5
    reported = np.where(flip, block["other"], block["reported"])
    other = np.where(flip, block["reported"], block["other"])
    return {**block, "reported": reported, "other": other}


def _pre_cue_stat_of_session(blocks: list[dict]) -> float | None:
    block = blocks[0]
    if block["n"] == 0:
        return None
    d_rep = circular_abs_diff(block["decoded"], block["reported"])
    d_oth = circular_abs_diff(block["decoded"], block["other"])
    return float(np.mean(d_rep < d_oth)) - 0.5  # departure from 0.5, matching the delivered mean_diff_from_half scale


def _cell_pre_cue_reported_item() -> dict:
    delivered = json.loads((ROOT / "results" / "pre_cue_state_and_reported_item_identity.json").read_text())
    delivered_per_session = {r["session"]: r["observed_fraction"]
                              for r in delivered["block_a"]["per_session_shuffled_report_null"]}
    delivered_pooled_a = delivered["block_a"]["pooled_a_primary"]
    delivered_pooled_c = delivered["block_a"]["pooled_c_bias_only_control"]

    root = data_root()
    behaviour = watters_behaviour(root)
    session_blocks, mismatches = [], []
    n_seen, n_with_arrays = 0, 0
    for session in iter_watters(root, bin_ms=100.0):
        n_seen += 1
        if session["status"] != "loaded":
            continue
        key = session["session"]
        if key not in delivered_per_session:
            continue  # not one of the 22 sessions the delivered artifact itself analysed to 'computed'
        # seed_prefix must match the delivered script's own literal string exactly: every stable_seed
        # tag derived from it (the reachability gate's own randomness, the ridge decoder's KFold shuffle
        # seed) depends on this string, and a different one silently reproduces a DIFFERENT session
        # population and different fold splits rather than the delivered analysis.
        result = _pre_cue_session_trial_arrays(session, behaviour, "pre_cue_state_and_reported_item_identity")
        if result is None:
            mismatches.append({"session": key, "reason": "recomputation_did_not_reach_computed_status"})
            continue
        n_with_arrays += 1
        if abs(result["primary_fraction"] - delivered_per_session[key]) >= REPRODUCTION_TOLERANCE:
            mismatches.append({"session": key, "recomputed": result["primary_fraction"],
                                "delivered": delivered_per_session[key]})
        session_blocks.append([{
            "n": result["n_test_trials"], "decoded": result["decoded_theta_test"],
            "reported": result["reported_theta"], "other": result["other_theta"],
        }])

    gate_ok = bool(n_with_arrays == len(delivered_per_session) and not mismatches)
    per_session_departure = [_pre_cue_stat_of_session(blocks) for blocks in session_blocks]
    per_session_departure = [v for v in per_session_departure if v is not None]
    real_recomputed_mean = float(np.mean(per_session_departure)) if per_session_departure else None
    reproduction_checks = {
        "n_sessions_matches": bool(n_with_arrays == len(delivered_per_session)),
        "n_sessions_with_exact_fraction_match": len(delivered_per_session) - len(mismatches),
        "recomputed_departure_matches_delivered": bool(
            real_recomputed_mean is not None
            and abs(real_recomputed_mean - delivered_pooled_a["mean_diff_from_half"]) < 1e-6),
    }

    permutation = {"primary": within_session_permutation_test(
        session_blocks, "within_session_permutation_control|pre_cue_reported_item",
        stat_of_session=_pre_cue_stat_of_session, shuffle_block=_pre_cue_shuffle_block)}

    real_reported = {
        "status": "tested", "mean_value": delivered_pooled_a["mean_diff_from_half"],
        "p_value": delivered_pooled_a["p_value"], "significant": delivered_pooled_a["significant"],
        "ci_lower": delivered_pooled_a["ci_lower"] - 0.5, "ci_upper": delivered_pooled_a["ci_upper"] - 0.5,
        "minimum_detectable_paired_difference_at_80pct_power":
            delivered_pooled_a["minimum_detectable_departure_from_half_at_80pct_power"],
    }
    return _assemble_cell(
        cell_name="pre_cue_state_leans_away_from_reported_item",
        corpus="multi_object_macaque_watters", n_sessions=len(session_blocks),
        delivered_artifact="results/pre_cue_state_and_reported_item_identity.json",
        reproduction_checks=reproduction_checks, gate_ok=gate_ok,
        real_by_stat={"primary": real_reported},
        between_session_control_by_stat={"primary": {
            "mean_value": delivered_pooled_c["mean_diff_from_half"], "p_value": delivered_pooled_c["p_value"],
            "significant": delivered_pooled_c["significant"]}},
        permutation_by_stat=permutation,
        why_at_risk="the pre-cue population state's below-half lean toward the object that will be "
                    "reported (not the cued object) -- the delivered decision list has no bias-only "
                    "voiding clause for a below-half departure (a declared gap in the rule), and the "
                    "between-session control fires in the same direction at larger magnitude; the "
                    "delivered artifact itself states this departure 'must never be read as a per-trial "
                    "neural result' on that basis. No spike-count/trial-index nuisance partial exists for "
                    "this fraction-based estimator (it is not a correlation), so only the primary "
                    "statistic is reported, not a raw/joint-partial pair.",
        mismatches=mismatches,
    )


# ============================================================================
# Shared cell assembly, branch decision
# ============================================================================

def _assemble_cell(cell_name, corpus, n_sessions, delivered_artifact, reproduction_checks, gate_ok,
                    real_by_stat, between_session_control_by_stat, permutation_by_stat, why_at_risk,
                    zero_drop_note=None, mismatches=None) -> dict:
    cell = {
        "cell_name": cell_name, "corpus": corpus, "n_sessions": n_sessions,
        "delivered_artifact": delivered_artifact, "why_at_risk": why_at_risk,
        "reproduction_gate": {"status": "reproduced" if gate_ok else "not_reproduced",
                               "tolerance": REPRODUCTION_TOLERANCE, "checks": reproduction_checks},
    }
    if zero_drop_note:
        cell["zero_drop_note"] = zero_drop_note
    if mismatches is not None:
        cell["reproduction_mismatches"] = mismatches
    if not gate_ok:
        cell["branch"] = BRANCH_GATE_FAILED
        return cell

    stats = list(real_by_stat.keys())
    real_significant = {s: bool(real_by_stat[s].get("significant")) for s in stats}
    real_direction = {s: ("positive" if (real_by_stat[s].get("mean_value") or 0) > 0 else "negative")
                       for s in stats}
    all_real_significant = all(real_significant.values())

    cell["real"] = real_by_stat
    cell["between_session_control_invalid"] = {
        **between_session_control_by_stat,
        "validity_note": "this control cannot confound a within-session estimator (see results/"
                          "bias_only_control_validity_simulation.json); reported here for completeness "
                          "only, never as evidence for or against this cell.",
    }
    cell["within_session_permutation_control_valid"] = permutation_by_stat

    if not all_real_significant:
        cell["branch"] = BRANCH_REAL_NOT_SIGNIFICANT
        cell["branch_significance_by_stat"] = real_significant
        return cell

    survives = all(
        permutation_by_stat[s].get("status") == "computed" and permutation_by_stat[s]["significant"]
        and permutation_by_stat[s]["direction"] == real_direction[s]
        for s in stats
    )
    if survives:
        cell["branch"] = BRANCH_SURVIVES
        return cell

    mdds = [real_by_stat[s].get("minimum_detectable_paired_difference_at_80pct_power", {}).get("mdd")
            for s in stats]
    mdds = [m for m in mdds if isinstance(m, (int, float))]
    if mdds and max(mdds) < MEANINGFUL_EFFECT_THRESHOLD_R_UNITS:
        cell["branch"] = BRANCH_POWERED_NULL
        cell["max_minimum_detectable_difference_across_load_bearing_stats"] = max(mdds)
    else:
        cell["branch"] = BRANCH_INCONCLUSIVE_UNDERPOWERED
    return cell


def main() -> None:
    t0 = time.time()
    print("loading multi-object macaque corpus", file=sys.stderr, flush=True)
    rows_arrays, zero_drop_multi_object = _load_multi_object_corpus()
    print(f"  {len(rows_arrays)} sessions with computable trial arrays, elapsed={time.time()-t0:.0f}s",
          file=sys.stderr, flush=True)

    cells = {}
    print("cell A: swap pooled within-item-count-level", file=sys.stderr, flush=True)
    cells["swap_pooled_within_item_count_level"] = _cell_swap_pooled_within_item_count_level(rows_arrays)
    print(f"  branch={cells['swap_pooled_within_item_count_level']['branch']} elapsed={time.time()-t0:.0f}s",
          file=sys.stderr, flush=True)

    print("cell B: swap level-2-only", file=sys.stderr, flush=True)
    cells["swap_level2_only"] = _cell_swap_level2_only(rows_arrays)
    print(f"  branch={cells['swap_level2_only']['branch']} elapsed={time.time()-t0:.0f}s",
          file=sys.stderr, flush=True)

    print("cell D: rate-free headline", file=sys.stderr, flush=True)
    cells["rate_free_headline"] = _cell_rate_free_headline()
    print(f"  branch={cells['rate_free_headline']['branch']} elapsed={time.time()-t0:.0f}s",
          file=sys.stderr, flush=True)

    print("cell C: pre-cue reported-item", file=sys.stderr, flush=True)
    cells["pre_cue_reported_item"] = _cell_pre_cue_reported_item()
    print(f"  branch={cells['pre_cue_reported_item']['branch']} elapsed={time.time()-t0:.0f}s",
          file=sys.stderr, flush=True)

    output = {
        "version": ANALYSIS_VERSION,
        "scope": "For every cell voided or left untested by this project's between-session bias-only "
                 "control, a within-session permutation control that CAN confound a within-session "
                 "estimator, applied and reported side by side with the real effect, the trial-level "
                 "nuisance partials and the (invalid) between-session control.",
        "cells_enumerated": [
            "swap_pooled_within_item_count_level (results/component_binding_bias_only_control.json, "
            "VOIDED)",
            "swap_level2_only (results/swap_versus_imprecision_by_item_count.json, VOIDED)",
            "pre_cue_reported_item (results/pre_cue_state_and_reported_item_identity.json, decision-list "
            "gap, the artifact's own text treats the departure as not separable from a session-level bias)",
            "rate_free_headline (results/behaviour_association_bias_only_sweep.json, NOT voided but the "
            "between-session control that failed to void it was itself underpowered -- reported "
            "'untested', not 'confirmed')",
        ],
        "framing_constraint": (
            "No cell in this artifact is reported as restored or confirmed relative to its status before "
            "the between-session control. A cell whose voiding rests on the between-session control alone "
            "is UNRESOLVED here -- neither established nor validly withdrawn -- unless it independently "
            f"reaches branch '{BRANCH_SURVIVES}' under the within-session permutation control at its own "
            "pre-declared threshold, in which case it is reported with its effect size and detection floor, "
            "as a new, independent finding under this control, not a reinstatement of any prior claim."
        ),
        "branch_decision_rule_declared_before_fitting": BRANCH_DECISION_RULE_DECLARED_BEFORE_FITTING,
        "meaningful_effect_threshold_r_units": MEANINGFUL_EFFECT_THRESHOLD_R_UNITS,
        "n_permutations_requested_per_within_session_control": N_PERM_WITHIN_SESSION,
        "zero_drop_accounting_multi_object_corpus_load": zero_drop_multi_object,
        "cells": cells,
        "status": "complete",
        "git_commit": git_commit(ROOT),
        "wall_clock_s": time.time() - t0,
    }
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(_json_safe(output), indent=2, allow_nan=False, default=float))
    print(json.dumps({name: cell["branch"] for name, cell in cells.items()}, indent=2))
    print(f"wall_clock_s={output['wall_clock_s']:.0f}", file=sys.stderr)


if __name__ == "__main__":
    main()
